### ISSUE TITLE
Allow providing multiple instances of a single rule

### ISSUE THREAD

**Issue by flangknecht** [kordamp/enforcer-gradle-plugin#15]
We've configured multiple instances of RequireGradleProperty enforcer rule. The last configured instance wins.

```kotlin
rule<RequireGradleProperty> {
    enabled.set(true)
    property.set("project.version")
    message.set("Project version must be specified.")
    regex.set(".*(\\d|-SNAPSHOT)\$")
    regexMessage.set("Project version must end in a number or \"-SNAPSHOT\".")
}
rule<RequireGradleProperty> {
    enabled.set(true)
    property.set("project.version")
    regex.set("\\d.*\$")
    regexMessage.set("Project version must start with a number.")
}
rule<RequireGradleProperty> {
    enabled.set(false)
    property.set("project.config.info.scm.developerConnection")
    regexMessage.set("project.config.info.scm.developerConnection must be specified.")
}
```

This configuration leads to no RequireGradleProperty rules being enforced.

Either multiple instances of this rule should be configurable or one rule should allow for multiple property rules to be defined.

Corresponding Maven XML:

```xml
<requireProperty>
                <property>project.version</property>
                <message>"Project version must be specified."</message>
                <regex>.*(\d|-SNAPSHOT)$</regex>
                <regexMessage>"Project version must end in a number or -SNAPSHOT."</regexMessage>
                <regex>\d.*$</regex>
                <regexMessage>"Project version must start with a number."</regexMessage>
              </requireProperty>
```

**Comment by aalmiray** [comment]
Rules may be able to be defined multiple times if they implement the `org.kordamp.gradle.plugin.enforcer.api.RepeatableEnforcerRule` interface. The guide will show which rules may be repeated.

With this feature these previous definitions should work

    rule<RequireGradleProperty> {
        property.set("version")
        message.set("Project version must be specified.")
        regex.set(".*(\\d|-SNAPSHOT)\$")
        regexMessage.set("Project version must end in a number or \"-SNAPSHOT\".")
    }
    rule<RequireGradleProperty> {
        property.set("version")
        regex.set("\\d.*\$")
        regexMessage.set("Project version must start with a number.")
    }

Note that the value of `property` should not use the `project.` prefix.
Also note that Kordamp DSL properties may not be evaluated in this way a separate rule for this DSL will be required.
