### ISSUE TITLE
Suppress banner output when -q option is given

### ISSUE THREAD

**Issue by portalsoup** [kordamp/enforcer-gradle-plugin#23]
Is there a way to suppress the following output?

    Kordamp Enforcer Gradle plugin 0.9.0. Consider becoming a patron at https://www.patreon.com/aalmiray

This is printing even with the `-q` flag.  After introducing this plugin, our CI pipelines began failing because a few tasks which do nothing but print out specific properties for our CI system are now printing out this message as well.  

If there isn't already, it would be very useful to have a way to suppress this output conditionally when in a fully automated environment where a human won't see it anyways.

**Comment by aalmiray** [comment]
This legend goes away after the 3rd showing as long `~/.gradle/caches` is persisted between runs. 

Currently there's no way to suppress it. This request is similar to https://github.com/jreleaser/jreleaser/issues/768 thus a fix is possible.

**Comment by portalsoup** [comment]
I see, since this runs in a fresh docker container each run I don't think it's possible to persist it between runs.  That's a bummer, unless this is fixed, this might mean that we can't adopt this plugin.

**Comment by aalmiray** [comment]
Understood. Most Kordamp plugins have this banner feature. It's not much of a problem to update them all to handle `-q` as suggested but it'll take a couple of weeks to get all the work sorted out and new versions released.

**Comment by portalsoup** [comment]
That would be fantastic.  We can maintain our current process in the meantime.  This plugin would be a huge benefit and simplification compared to our current approach.

**Comment by aalmiray** [comment]
Version `0.10.0` has the fix
