### ISSUE TITLE
Enforcer rules are transitively pulled from dependencies project??

### ISSUE THREAD

**Issue by rpost** [kordamp/enforcer-gradle-plugin#28]
Long story short: I want to ban junit4 in some gradle subproject (let's call it A) and then use this subproject A and junit4 in subproject B. Enforcer plugin complains for junit4 present in subproject B. Why?

SSCCE: https://github.com/rpost/gradle-enforcer-bug

i get:

![image](https://user-images.githubusercontent.com/1088047/210875371-3861dd86-72f9-421e-bc1f-e92c4933e62c.png)

despite rule being present only in "no-junit-please" subproject:

![image](https://user-images.githubusercontent.com/1088047/210875579-81979abe-6b3d-4aeb-86c6-6df3993e365c.png)

**Comment by aalmiray** [comment]
Released in v0.13.0 -> https://github.com/kordamp/enforcer-gradle-plugin/releases/tag/v0.13.0
