### ISSUE TITLE
Outdated commons-lang3 version

### ISSUE THREAD

**Issue by binkley** [kordamp/enforcer-gradle-plugin#33]
While using Enforcer plugin and DependencyCheck plugin together in the same build, I found an issue with transitive dependencies, specifically the "commons-lang3" version used by Enforcer is older, and breaks DependencyCheck.

See https://github.com/kordamp/enforcer-gradle-plugin/issues/17#issuecomment-2271201919 and following comments for more details.

To address, I forced the Enforcer plugin to use an updated commons-lang3 version, 3.15.0.
The example used may the the root of this issue: pulling in "enforcer" rather than "build-enforcer" plugin in `settings.gradle` changes the classpath for other plugins, so the conflicting versions of commons-lang3 becomes apparent.

**Comment by aalmiray** [comment]
🎉 This issue has been resolved in `v0.14.0` ([Release Notes](https://github.com/kordamp/enforcer-gradle-plugin/releases/tag/v0.14.0))
