### ISSUE TITLE
Add rules to enforce kordamp.base properties

### ISSUE THREAD

**Issue by leonard84** [kordamp/enforcer-gradle-plugin#5]
We'd like to be able to enforce, that projects have to set certain properties of the kordamp `config`, for example the `scm` properties.

**Comment by aalmiray** [comment]
There is a base class https://github.com/kordamp/enforcer-gradle-plugin/blob/master/core/enforcer-rules/src/main/groovy/enforcer/rules/kordamp/AbstractKordampEnforcerRule.groovy that can be used to implement other Kordamp related rules.

**Comment by aalmiray** [comment]
See #16
